# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bc306ad88ee9c23caee3b6e23694c3bdffb7cd7a9c6ac5675e54f266f1e30a3f72f355784c013d40d0190c81ad27fd02f842947c2ae303b68bc5d48b2cbc56e

test:
  secret_key_base: 5b1e58bf5a4895540be54a20097fdd51c052878f2bdf0ea0a8cb19a9b8f4be81afb5199aacd1735522db5f80ae7aacd7cc3f57328def2651f245d0528a72b8f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
